/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.idiotleon

class App {
    val greeting: String
        get() {
            return "Welcome to the real world~"
        }
}

fun main(args: Array<String>) {
    println(App().greeting)
}